openapi: 3.0.0
info:
  title: Informer API
  description: API для управления информерами в админке
  version: "1.0"
servers:
  - url: /
paths:
  /api/v1/location:
    get:
      summary: Получение информации о всех возможных путях расположения информера из таблицы location
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
  /api/v1/informer:
    get:
      summary: Получение списка всех информеров с пагинацией
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
            minimum: 0
          description: Смещение списка (начиная с какого элемента)
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          description: Максимальное количество элементов в списке
      responses:
        '200':
          description: Список всех информеров
          content:
            application/json:
              $ref: '#/components/schemas/InformerList'

    post:
      summary: Создание информера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformerCreate'
      responses:
        '201':
          description: Информер успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FullInformer'
        '400':
          description: Неверный запрос, ошибка валидации
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Описание ошибки валидации
              example:
                error: "Ошибка валидации: поле 'name' не может быть пустым"
  /api/v1/informer/{id}:
    get:
      summary: Получение информера для редактирования
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Уникальный идентификатор информера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullInformer'
    delete:
      summary: Удаление информера
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Уникальный идентификатор информера
      responses:
        '204':
          description: Информер успешно удален
        '404':
          description: Информер не найден
    put:
      summary: Обновление информера
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Уникальный идентификатор информера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FullInformer'
      responses:
        '200':
          description: Информер успешно обновлен
        '400':
          description: Неверный запрос, ошибка валидации
        '404':
          description: Информер не найден
    patch:
      summary: Частичное обновление информера (overkill?)
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Уникальный идентификатор информера
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformerPatch'
      responses:
        '200':
          description: Информер успешно обновлен
        '400':
          description: Неверный запрос, ошибка валидации
        '404':
          description: Информер не найден
components:
  schemas:
    InformerList:
      type: array
      items:
        type: object
        required:
          - class
          - id
          - name
          - updatedAt
          - createdBy
          - isActive
          - displayOrder
        properties:
          class:
            type: integer
            format: int64
            description: Тип информера
          id:
            type: integer
            format: int64
            description: Уникальный идентификатор информера
          name:
            type: string
            description: Название информера
          updatedAt:
            type: string
            format: date-time
            description: Дата обновления информера
          createdBy:
            type: integer
            format: int64
            description: Идентификатор пользователя, создавшего информер
          isActive:
            type: boolean
            description: Флаг активности информера
          displayOrder:
            type: integer
            format: int64
            description: Порядок отображения информера
      example:
        - class: 1
          id: 1
          name: "Новый Информер"
          updatedAt: "2024-04-17T12:27:52.000Z"
          createdBy: 124
          isActive: true
          displayOrder: 1
    InformerCreate:
      type: object
      required:
        - name
        - locationId
        - isActive
        - view
        - type
        - displayOrder
        - content
      properties:
        name:
          type: string
          maxLength: 255
          description: Название информера
        locationId:
          type: integer
          format: int64
          description: Уникальный идентификатор местоположения информера
        isActive:
          type: boolean
          description: Флаг активности информера
        view:
          type: string
          enum:
            - web
            - mobile
          description: Вид информера
        class:
          type: integer
          format: int64
          description: Вид информера, например, интрукция или банер
        displayOrder:
          type: integer
          format: int64
          description: Порядок отображения информера
        content:
          type: array
          items:
            type: object
            required:
              - type
              - value
            properties:
              type:
                type: integer
                format: int64
                description: Тип контента, например, заголовок или буллетпойнт
              value:
                type: string
                description: Значение, которое содержит выбранный тип контента
      example:
        name: "Новый Информер"
        locationId: 1
        isActive: true
        view: "web"
        class: 1
        displayOrder: 1
        content:
          - type: 1
            value: "Pater noster, qui es in caelis"
        createdBy: 124
    InformerPatch:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: Название информера
        locationId:
          type: integer
          format: int64
          description: Уникальный идентификатор местоположения информера
        isActive:
          type: boolean
          description: Флаг активности информера
        view:
          type: string
          enum:
            - web
            - mobile
          description: Вид информера
        type:
          type: integer
          format: int64
          description: Тип информера
        displayOrder:
          type: integer
          format: int64
          description: Порядок отображения информера
        content:
          type: object
          required:
            - type
            - value
          properties:
            type:
              type: integer
              format: int64
              description: Тип содержимого информера
            value:
              type: string
              description: Значение содержимого информера
      example:
        content:
          type: 2
          value: "sanctificetur nomen Tuum"
    FullInformer:
      description: Информер успешно создан/обновлен
      properties:
        message:
          type: string
          description: Сообщение об успешном создании/обновлении информера
        informer:
          type: object
          description: Полная информация о созданном информере
          properties:
            id:
              type: integer
              format: int4
              description: Уникальный идентификатор информера
            name:
              type: string
              description: Название информера
            locationId:
              type: integer
              format: int2
              description: Идентификатор связанного местоположения
            isActive:
              type: boolean
              description: Статус активности информера
            view:
              type: string
              enum: [web, mobile]
              description: Платформа отображения информера
            class:
              type: integer
              format: int2
              description: Идентификатор класса информера, например 'Инструкция'
            displayOrder:
              type: integer
              format: int2
              description: Порядок отображения информера на странице портала поставщиков
            layoutId:
              type: integer
              format: int4
              description: Идентификатор макета отображения
            createdBy:
              type: int8,
              description: ИД пользователя, создавшего информер
            createdAt:
              type: string
              format: date-time
              description: Время создания информера
            updatedAt:
              type: string
              format: date-time
              description: Время последнего обновления информера
            layout:
              type: object
              description: Информация о макете
              properties:
                id:
                  type: integer
                  format: int4
                  description: Уникальный идентификатор макета
                content:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - value
                    properties:
                      type:
                        type: integer
                        format: int64
                        description: Тип контента, например, заголовок или буллетпойнт
                      value:
                        type: string
                        description: Значение, которое содержит выбранный тип контента
                isActual:
                  type: boolean
                  description: Актуальность макета
                createdAt:
                  type: string
                  format: date-time
                  description: Время создания макета
      example:
        message: "Информер успешно создан/обновлен"
        informer:
          id: 88
          name: "Название информера"
          locationId: 1
          isActive: true
          view: "web"
          class: 2
          displayOrder: 3
          layoutId: 4
          createdBy: 666
          createdAt: "2024-04-20T12:34:56Z"
          updatedAt: "2024-04-20T12:34:56Z"
          layout:
            id: 4
            content: [
              {
               type: 1,
               value: "Pater noster, qui es in caelis" 
              }
            ]
            isActual: true
            createdAt: "2024-04-20T12:34:56Z"

    Location:
      type: array
      items:
        type: object
        properties:
          parent:
            type: string
            description: Название родительского элемента
          childs:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: Уникальный идентификатор дочернего элемента
                name:
                  type: string
                  description: Название дочернего элемента
                url:
                  type: string
                  format: uri
                  description: URL дочернего элемента
                manualMax:
                  type: int2
                  description: Максимальное кол-во инструкций на странице
                bannerMax:
                  type: int2
                  description: Максимальное кол-во баннеров на странице
                pollMax:
                  type: int2
                  description: Максимальное кол-во опросов на странице
      example:
        - parent: "Цены и скидки"
          childs:
            - id: 456
              name: "Индекс цен"
              url: "https://seller-portal-stage.wildberries.ru/prices-index"
              manualMax: 3
              bannerMax: 5
              pollMax: 7
