openapi: 3.0.0
info:
  title: Informer API
  description: API для управления информерами в админке
  version: "1.0"
servers:
  - url: "/"
paths:
  /api/v1/informer/location:
    get:
      summary: Получение ссылок на все разделы Портала Поставщиков из справочника 'location'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
  /api/v1/informer/list:
    post:
      summary: Получение списка всех информеров с пагинацией
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sort:
                  type: object
                  description: Параметры для сортировки списка информеров
                  properties:
                    columnName:
                      type: string
                      description: Поле, по которому производится сортировка
                    order:
                      type: string
                      enum: [asc, desc]
                      description: Порядок сортировки (по возрастанию или убыванию)
                filter:
                  type: object
                  description: Фильтр для информеров
                  properties:
                    locationId: 
                      type: integer
                      description: ИД раздела портала поставщиков из справочника location
                cursor:
                  type: object
                  description: Параметры для управления пагинацией
                  properties:
                    next:
                      type: boolean
                      description: Флаг, указывающий на наличие следующей страницы
                    n:
                      type: integer
                      description: Количество элементов на странице
                    informerId:
                      type: integer
                      description: ИД информера, на котором завершилась текущая страница
      responses:
        '200':
          description: Список всех информеров
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformerList'
  /api/v1/informer:
    post:
      summary: Создание/обновление информера. Зависит от того, передается ли в теле запроса ИД.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformerCreate'
      responses:
        '201':
          description: Информер успешно создан/обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostInformer'
        '400':
          description: Неверный запрос, ошибка валидации
          content:
            application/json:
              schema:
                 $ref: '#/components/schemas/ErrorResponce' 
  /api/v1/informer/content:
    post:
      summary: Сохранение контента информера
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/InformerContent'
      responses:
        '201':
          description: Контент информера создан/обновлен
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/InformerContent'
        '400':
          description: Неверный запрос, ошибка валидации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponce' 
  /api/v1/informer/{id}:
    get:
      summary: Получение контента информера для редактирования
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Уникальный идентификатор информера
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InformerContent'
    delete:
      summary: Удаление информера
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Уникальный идентификатор информера
      responses:
        '204':
          description: Информер успешно удален
        '404':
          description: Информер не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponce'
  /api/v1/informer/forCurrentPage:
    get:
      summary: Получение актуальных информеров для раздела портала поставщиков
      parameters:
        - in: query
          name: location
          schema:
            type: string
            format: uri
          required: true
          description: Раздел портала, для которого запрашиваются информеры
      responses:
        '200':
          description: Список актуальных информеров для указанного раздела
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForCurrentPage'
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponce'
  /api/v1/informer/feedback:
    post:
      summary: Добавление оценки на информер
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InformerRatingInput'
      responses:
        '200':
          description: Оценка информера успешно сохранена
        '400':
          description: Неверный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponce'
components:
  schemas:
    InformerList:
      type: array
      items:
        type: object
        required:
          - id
          - locationId
          - type
          - name
          - updatedAt
          - createdBy
          - isActive
          - displayOrder
        properties:
          locationId:
            type: integer
            format: int2
            description: ИД расположения информера
          type:
            type: string
            description: Тип информера
          id:
            type: integer
            format: int64
            description: Уникальный идентификатор информера
          name:
            type: string
            description: Название информера
          updatedAt:
            type: string
            format: date-time
            description: Дата обновления информера
          createdBy:
            type: integer
            format: int64
            description: Идентификатор пользователя, создавшего информер
          isActive:
            type: boolean
            description: Флаг активности информера
          displayOrder:
            type: integer
            format: int64
            description: Порядок отображения информера
      example:
        - id: 1
          locationId: 453
          type: Manual
          name: "Новый Информер"
          updatedAt: "2024-04-17T12:27:52.000Z"
          createdBy: 124
          isActive: true
          displayOrder: 1
    InformerCreate:
      type: object
      required:
        - name
        - isActive
        - type
        - displayOrder
      properties:
        id:
          type: integer
          description: ИД информера
        name:
          type: string
          maxLength: 255
          description: Название информера
        isActive:
          type: boolean
          description: Флаг активности информера
        type:
          type: string
          description: Вид информера, например, инструкция или баннер
        displayOrder:
          type: integer
          format: int64
          description: Порядок отображения информера
      example:
        id: 88
        name: "Интересная инструкция"
        locationId: 1
        isActive: true
        type: Manual
        displayOrder: 1
    InformerPatch:
      type: object
      properties:
        name:
          type: string
          maxLength: 255
          description: Название информера
        locationId:
          type: integer
          format: int64
          description: Уникальный идентификатор местоположения информера
        isActive:
          type: boolean
          description: Флаг активности информера
        view:
          type: string
          enum:
            - web
            - mobile
          description: Вид информера
        type:
          type: integer
          format: int64
          description: Тип информера
        displayOrder:
          type: integer
          format: int64
          description: Порядок отображения информера
        content:
          type: object
          required:
            - type
            - value
          properties:
            type:
              type: integer
              format: int64
              description: Тип содержимого информера
            value:
              type: string
              description: Значение содержимого информера
      example:
        content:
          type: 2
          value: "sanctificetur nomen Tuum"
    PostInformer:
      type: object
      description: Информер создан/обновлен
      properties:
        id:
          type: integer
          description: Уникальный ИД информера
        type:
          type: string
          description: Тип информера, например 'Инструкция'
    FullInformerDeprecated:
      type: object
      description: Информер успешно создан/обновлен
      properties:
        id:
          type: integer
          format: int4
          description: Уникальный идентификатор информера
        name:
          type: string
          description: Название информера
        locationId:
          type: integer
          format: int2
          description: Идентификатор связанного местоположения
        isActive:
          type: boolean
          description: Статус активности информера
        view:
          type: string
          enum: [web, mobile]
          description: Платформа отображения информера
        type:
          type: string
          description: Идентификатор класса информера, например 'Инструкция'
        displayOrder:
          type: integer
          format: int2
          description: Порядок отображения информера на странице портала поставщиков
        layoutId:
          type: integer
          format: int4
          description: Идентификатор макета отображения
        createdBy:
          format: integer
          description: ИД пользователя, создавшего информер
        createdAt:
          type: string
          format: date-time
          description: Время создания информера
        updatedAt:
          type: string
          format: date-time
          description: Время последнего обновления информера
        layout:
          type: object
          description: Информация о макете
          properties:
            id:
              type: integer
              format: int4
              description: Уникальный идентификатор макета
            content:
              type: array
              items:
                type: object
                required:
                  - type
                  - value
                properties:
                  type:
                    type: integer
                    format: int64
                    description: Тип контента, например, заголовок или буллетпойнт
                  value:
                    type: string
                    description: Значение, которое содержит выбранный тип контента
            isActual:
              type: boolean
              description: Актуальность макета
            createdAt:
              type: string
              format: date-time
              description: Время создания макета
      example:
        id: 88
        name: "Название информера"
        locationId: 1
        isActive: true
        view: "web"
        type: Manual
        displayOrder: 3
        layoutId: 4
        createdBy: 666
        createdAt: "2024-04-20T12:34:56Z"
        updatedAt: "2024-04-20T12:34:56Z"
        layout:
          id: 4
          content: [
            {
              type: 1,
              value: "Pater noster, qui es in caelis" 
            }
          ]
          isActual: true
          createdAt: "2024-04-20T12:34:56Z"
    Location:
      type: array
      items:
        type: object
        properties:
          parentId:
            type: integer
            description: ИД родителя
          parentName:
            type: string
            description: Название родительского элемента
          childs:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  description: Уникальный идентификатор дочернего элемента
                name:
                  type: string
                  description: Название дочернего элемента
                url:
                  type: string
                  format: uri
                  description: URL дочернего элемента
                manualMax:
                  type: integer
                  format: int2
                  description: Максимальное количество инструкций на странице
                bannerMax:
                  type: integer
                  format: int2
                  description: Максимальное количество баннеров на странице
                pollMax:
                  type: integer
                  format: int2
                  description: Максимальное количество опросов на странице
      example:
        - parentId: 345
          parentName: "Цены и скидки"
          childs:
            - id: 456
              name: "Индекс цен"
              url: "prices-index"
              manualMax: 3
              bannerMax: 5
              pollMax: 7
    ErrorResponce:
      type: object
      properties:
        data:
          type: string
          description: NULL в случае ошибки
        error:
          type: boolean
          description: Признак наличия ошибки
        errorText:
          type: string
          description: Текст ошибки
        additionalErrors:
          type: object
          description: Дополнительные ошибки (если есть)


    InformerRatingInput:
      type: object
      required:
        - layoutId
        - feedback
        - supplier_id
      properties:
        layoutId:
          type: integer
          description: ИД макета информера
        feedback:
          type: string
          enum: [like, dislike]
          description: Оценка информера (like или dislike)
        supplier_id:
          type: integer
          description: ИД пользователя, оценившего информер
    InformerContent:
      type: object
      properties:
        hasFeedback:
          type: boolean
          description: Наличие обратной связи
        view:
          type: string
          enum:
            - web
            - mobile
          description: Вид информера
        content:
          type: array
          items:
            type: object
            required:
              - type
              - value
            properties:
              type:
                type: integer
                format: int64
                description: Тип контента
              value:
                type: string
                description: Значение контента
    ForCurrentPage:
      type: array
      items:
        type: object
        required:
          - type
          - name
          - isActive
          - displayOrder
          - informerContent
        properties:
          type:
            type: string
            description: Тип информера
          name:
            type: string
            description: Название информера
          isActive:
            type: boolean
            description: Флаг активности информера
          displayOrder:
            type: integer
            format: int64
            description: Порядок отображения информера
          informerContent:
            $ref: '#/components/schemas/InformerContent'